language: node_js
node_js:
    - "12"
install:
    - npm ci
script:
    - npm run lint
    - npm run test
    - npm run tsc
    - npm run build
    - npm run test:build
after_success:
    - npm install -g codecov
    - codecov
    - npm run release
notifications:
    email: false
sudo: required
