language: node_js
node_js:
    - 10
install:
    - npm ci
    - npm install -g codecov
script:
    - npm run lint
    - npm run test
    - npm run tsc
after_success:
  - codecov
notifications:
  email: false
sudo: required
deploy:
  provider: npm
  email: michal@fabulator.cz
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
