language: node_js
node_js:
    - 11
install:
    - npm ci
script:
    - npm run lint
    - npm run test
    - npm run tsc
after_success:
    - npm run release
notifications:
    email: false
sudo: required
